[PYTHON] Add unit tests showing bad expression evaluation
When an expression evaluates a function, A, which itself contains an expression
evaluating another function, B, then the evaluation fails.

Reason is because only the local scope of A is passed to the evaluation. And
B is in the global scope.

    fjardon@yoda 17:09:21 ~/workspace/ribosome/tests
    $ ../ribosome.py --rna functions2.py.dna > function2.py.rna

    fjardon@yoda 17:09:49 ~/workspace/ribosome/tests
    $ python ./function2.py.rna
    Traceback (most recent call last):
      File "./function2.py.rna", line 288, in <module>
        template()
      File "./function2.py.rna", line 283, in template
        Block.dot('Colours: @{colours()} Shapes: @{shapes()}', locals())
      File "./function2.py.rna", line 216, in dot
        Block.add(line, bind)
      File "./function2.py.rna", line 200, in add
        val = eval(expr, bind)
      File "<string>", line 1, in <module>
    NameError: name 'colours' is not defined

Patch submitted under MIT/X11 liense